spring.application.name=TrustInsure

spring.datasource.url = jdbc:postgresql://localhost:5432/trustinsure
spring.datasource.username=adm
spring.datasource.password=adminadmin
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = create

